project_name: largo-installer

builds:
  - id: largo-installer
    main: ./cmd/largo-installer
    binary: largo-installer
    ldflags:
      - -s -w -X github.com/MohammedMogeab/largo-installer/internal/buildinfo.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

archives:
  - id: archive
    builds: [largo-installer]
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: git

release:
  draft: true

